name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - "**"

jobs:
  audit-action:
    name: Audit Action
    permissions: "write-all"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Smart Contract Audit
        uses: ahnafalfariza/smart-contract-audit@test-call-action
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          myToken: ${{ secrets.GITHUB_TOKEN }}
