name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - "**"

jobs:
  audit-action:
    name: Audit Action
    permissions: "write-all"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: contract

      - name: List directory first co
        run: |
          echo "Contents of the current directory:"
          ls -la
 
      - name: Checkout tool
        uses: actions/checkout@v4
        with:
          repository: ahnafalfariza/scavene
          ref: test-ci

      - name: List directory contents
        run: |
          echo "Contents of the current directory:"
          ls -la

      - name: Smart Contract Audit
        uses: ahnafalfariza/scavene@test-ci
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          myToken: ${{ secrets.GITHUB_TOKEN }}
